---
name: Web Components Polyfill Bundle
description: Bundle of web component polyfills for IE 11+
resources:
  - src: dist/**
    dest: ./
latest-only: true
docs: https://github.com/byuweb/web-component-polyfills